name: Update Activity Graph
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Generate Activity Graph
        uses: Ashutosh00710/github-readme-activity-graph@master
        with:
          USERNAME: lifeofsankar
          THEME: tokyo-night
          OUTPUT_PATH: ./github-metrics.svg
